### ISSUE TITLE
Retrieve `security` information from the corresponding controller/action

### ISSUE THREAD

**Issue by keichinger** [Becklyn/BecklynRouteTreeBundle#13]
In the past we've already discussed this:
To minimize code duplication it'd be super nice if we could retrieve `security` information from a route's corresponding controller and/or action, depending on where the `@Security` annotation has been declared. Since right now one needs add a `@Security` annotation to a controller/action and then also duplicate the information over to the corresponding route in order to have the RouteTree/Menu adapt it.

Things that might need to be considered when implementing this feature:
- Check whether honoring `@Security` through inheritance works as expected (aka. when a base class controller has `@Security("is_granted('ROLE_ADMIN')")` then any derived controller automatically inherits it.
- Routes using the `FrameworkBundle:Redirect:*` controller and action need to be followed to their corresponding target (at least if it's internal) and then use the target controller's `@Security` information

**Comment by apfelbox** [comment]
This is now included
