### ISSUE TITLE
Ability to manipulate positioning

### ISSUE THREAD

**Issue by keichinger** [Becklyn/BecklynRouteTreeBundle#16]
For the RouteTreeBundle I'd love to have the ability to manipulate the positioning of a route inside the tree without having to re-position the route definitions inside the `routing.yml`.

Imagine a feature that works similarly to Egeloen's OrderedFormBundle with an option to set a route before or after another.

**Comment by lukasbrodbeck** [comment]
I like this idea, but I'd prefer to make an (optional) list of route entries, which are then rendered in this order. Every entry, which is not in the list gets rendered afterwards in the current order.

**Comment by apfelbox** [comment]
@lukasbrodbeck where would you store this list of entries? You would probably need to add a list to every single entry in the tree.

**Comment by apfelbox** [comment]
You can do that now via `priority`
